version: 2.1


orbs:
  ruby: circleci/ruby@0.1.2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    steps:
      - checkout
      - run:
          name: Install bundler
          command: gem install bundler:2.0.2
      - ruby/bundle-install
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - .
  rspec:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - run:
          name: Install bundler
          command: gem install bundler:2.0.2
      - ruby/bundle-install
      - run:
          name: Run rspec
          command: bundle exec rspec
  rubocop:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - run:
          name: Install bundler
          command: gem install bundler:2.0.2
      - ruby/bundle-install
      - run:
          name: Check the code with rubocop
          command: bundle exec rubocop --auto-correct --disable-uncorrectable
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - rspec:
          requires:
            - build
      - rubocop:
          requires:
            - rspec
      - deploy:
          requires:
            - rubocop
          filters:
            branches:
              only: master
